package com.fptproject.SWP391.model;

import java.util.Date;
import java.util.HashMap;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
/**
 *
 * @author admin
 */
public class Mail {

    public void send(Appointment appointment, AppointmentDetail[] appoitmentDetail, Customer customer, Dentist dentist, HashMap<String, Service> serviceMap) {

        final String user = "vinhlgse161135@fpt.edu.vn";//change accordingly  
        final String pass = "wzducphbhryilmko";//change accordingly  

        //1st step) Get the session object    
        Properties props = new Properties();
        props.setProperty("mail.smtp.host", "smtp.gmail.com");//change accordingly  
        props.setProperty("mail.smtp.port", "587");
        props.setProperty("mail.smtp.auth", "true");
        props.setProperty("mail.smtp.starttls.enable", "true");

        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(user, pass);
            }
        });
        //2nd step)compose message  
        try {
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(user));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(customer.getEmail()));
            //get 2 appointment detail
            String firstAppointmentDetail = "";
            String secondAppointmentDetail = "";

            if (appoitmentDetail.length == 2) {
                secondAppointmentDetail = "<p style=\"margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 21px;\"><span style=\"font-size:14px; font-weight: bold;\">" + "You have booked service \"" + serviceMap.get(appoitmentDetail[1].getServiceId()).getServiceName() + "\" in slot " + appoitmentDetail[1].getSlot() + ".</span></p>\n"
                        + "<p style=\"margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 21px;\"><span style=\"font-size:14px;\"> </span><br/></p>\n";
                firstAppointmentDetail = "You have booked service \"" + serviceMap.get(appoitmentDetail[0].getServiceId()).getServiceName() + "\" in slot " + appoitmentDetail[0].getSlot() + ".";
            }
            if (appoitmentDetail.length == 1) {
                firstAppointmentDetail = "You have booked service \"" + serviceMap.get(appoitmentDetail[0].getServiceId()).getServiceName() + "\" in slot " + appoitmentDetail[0].getSlot() + ".";
            }

            String msg = "<!DOCTYPE html>\n"
                    + "\n"
                    + "<html lang=\"en\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:v=\"urn:schemas-microsoft-com:vml\">\n"
                    + "<head>\n"
                    + "<title></title>\n"
                    + "<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n"
                    + "<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>\n"
                    + "<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->\n"
                    + "<style>\n"
                    + "		* {\n"
                    + "			box-sizing: border-box;\n"
                    + "		}\n"
                    + "\n"
                    + "		body {\n"
                    + "			margin: 0;\n"
                    + "			padding: 0;\n"
                    + "		}\n"
                    + "\n"
                    + "		a[x-apple-data-detectors] {\n"
                    + "			color: inherit !important;\n"
                    + "			text-decoration: inherit !important;\n"
                    + "		}\n"
                    + "\n"
                    + "		#MessageViewBody a {\n"
                    + "			color: inherit;\n"
                    + "			text-decoration: none;\n"
                    + "		}\n"
                    + "\n"
                    + "		p {\n"
                    + "			line-height: inherit\n"
                    + "		}\n"
                    + "\n"
                    + "		.desktop_hide,\n"
                    + "		.desktop_hide table {\n"
                    + "			mso-hide: all;\n"
                    + "			display: none;\n"
                    + "			max-height: 0px;\n"
                    + "			overflow: hidden;\n"
                    + "		}\n"
                    + "\n"
                    + "		@media (max-width:620px) {\n"
                    + "			.desktop_hide table.icons-inner {\n"
                    + "				display: inline-block !important;\n"
                    + "			}\n"
                    + "\n"
                    + "			.icons-inner {\n"
                    + "				text-align: center;\n"
                    + "			}\n"
                    + "\n"
                    + "			.icons-inner td {\n"
                    + "				margin: 0 auto;\n"
                    + "			}\n"
                    + "\n"
                    + "			.row-content {\n"
                    + "				width: 100% !important;\n"
                    + "			}\n"
                    + "\n"
                    + "			.mobile_hide {\n"
                    + "				display: none;\n"
                    + "			}\n"
                    + "\n"
                    + "			.stack .column {\n"
                    + "				width: 100%;\n"
                    + "				display: block;\n"
                    + "			}\n"
                    + "\n"
                    + "			.mobile_hide {\n"
                    + "				min-height: 0;\n"
                    + "				max-height: 0;\n"
                    + "				max-width: 0;\n"
                    + "				overflow: hidden;\n"
                    + "				font-size: 0px;\n"
                    + "			}\n"
                    + "\n"
                    + "			.desktop_hide,\n"
                    + "			.desktop_hide table {\n"
                    + "				display: table !important;\n"
                    + "				max-height: none !important;\n"
                    + "			}\n"
                    + "		}\n"
                    + "	</style>\n"
                    + "</head>\n"
                    + "<body style=\"background-color: #283C4B; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"nl-container\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #283C4B;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<div class=\"spacer_block\" style=\"height:20px;line-height:20px;font-size:1px;\"> </div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-2\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #283C4B;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #333; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-left: 15px; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"image_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"width:100%;padding-right:0px;padding-left:0px;\">\n"
                    + "<div style=\"line-height:10px\"><img alt=\"Image\" src=\"https://static.crozdesk.com/web_app_library/providers/logos/000/012/527/box/doccure-1618394200-logo.png?1618394200\" style=\"display: block; height: 120px; border: 0; width: 150px; max-width: 100%;\" title=\"Image\" width=\"236\"/></div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-3\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #283C4B;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #53e2f1; color: #333; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-left: 10px; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"text_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:30px;\">\n"
                    + "<div style=\"font-family: sans-serif\">\n"
                    + "<div class=\"txtTinyMce-wrapper\" style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #FFFFFF; line-height: 1.2; font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\">\n"
                    + "<p style=\"margin: 0; font-size: 18px; text-align: left;\"><span style=\"font-size:24px; font-weight:bold;\">Hello " + customer.getPersonalName() + ",</span></p>\n"
                    + "<p style=\"margin: 0; font-size: 18px; text-align: left;\"><span style=\"font-size:24px; font-weight:bold;\">This is your booking confirmation! </span><br/></p>\n"
                    + "</div>\n"
                    + "</div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-4\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #283C4B;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n" + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #333; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-top: 0px; padding-bottom: 10px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"text_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"padding-bottom:5px;padding-left:30px;padding-right:30px;padding-top:25px;\">\n"
                    + "<div style=\"font-family: sans-serif\">\n"
                    + "<div class=\"txtTinyMce-wrapper\" style=\"font-size: 12px; mso-line-height-alt: 18px; color: #283C4B; line-height: 1.5; font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\">\n"
                    + "<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 21px;\"><span style=\"font-size:14px;\">We look forward to welcoming you to our clinique on <span style=\"color:red; font-weight: bold;\">" + appointment.getMeetingDate() + "</span>.</span><br/></p>\n"
                    + "<p style=\"margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 21px;\"><span style=\"font-size:14px;\">Our professional and friendly staff are committed to ensuring your visit is both enjoyable and comfortable.</span></p>\n"
                    + "<p style=\"margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 21px;\"><span style=\"font-size:14px;\"> </span><br/></p>\n"
                    + "<p style=\"margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 21px;\"><span style=\"font-size:14px; font-weight:bold;\">" + firstAppointmentDetail + "</span></p>\n"
                    + "<p style=\"margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 21px;\"><span style=\"font-size:14px;\"> </span><br/></p>\n"
                    + secondAppointmentDetail
                    + "<p style=\"margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 21px;\"><span style=\"font-size:14px;\">Should you have any requests prior to your stay, please do not hesitate to contact us and we will endeavor to assist you whenever possible.</span></p>\n"
                    + "<p style=\"margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 21px;\"><span style=\"font-size:14px;\"> </span><br/></p>\n"
                    + "<p style=\"margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 21px;\"><span style=\"font-size:14px;\">Thanks & Best Regards,</span></p>\n"
                    + "<p style=\"margin: 0; font-size: 12px; text-align: left; mso-line-height-alt: 21px;\"><span style=\"font-size:14px;\">" + dentist.getPersonalName() + ", <em>Your Dentist</em></span></p>\n"
                    + "</div>\n"
                    + "</div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"button_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"padding-bottom:10px;padding-left:30px;padding-right:10px;padding-top:10px;text-align:left;\">\n"
                    + "<!--[if mso]><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"\" style=\"height:44px;width:123px;v-text-anchor:middle;\" arcsize=\"0%\" strokeweight=\"0.75pt\" strokecolor=\"#85D874\" fillcolor=\"#FFFFFF\"><w:anchorlock/><v:textbox inset=\"0px,0px,0px,0px\"><center style=\"color:#85D874; font-family:Arial, sans-serif; font-size:16px\"><![endif]--><a href=\"\" style=\"text-decoration:none;display:inline-block;color:#53e2f1;background-color:#FFFFFF;border-radius:0px;width:auto;border-top:1px solid #53e2f1;font-weight:undefined;border-right:1px solid #53e2f1;border-bottom:1px solid #53e2f1;border-left:1px solid #53e2f1;padding-top:5px;padding-bottom:5px;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;\" target=\"_blank\"><span style=\"padding-left:20px;padding-right:20px;font-size:16px;display:inline-block;letter-spacing:normal;\"><span style=\"font-size: 16px; line-height: 2; word-break: break-word; mso-line-height-alt: 32px;\">Contact Us</span></span></a>\n"
                    + "<!--[if mso]></center></v:textbox></v:roundrect><![endif]-->\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-5\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #F6F6F6; color: #333; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"33.333333333333336%\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"image_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"width:100%;padding-right:0px;padding-left:0px;padding-top:5px;\">\n"
                    + "<div align=\"center\" style=\"line-height:10px\"><img alt=\"Image\" src=\"https://media.istockphoto.com/photos/dentists-office-in-barcelona-medical-workers-portrait-picture-id687663822?k=20&m=687663822&s=612x612&w=0&h=rKaLezUTRp6ovaVbycpTLI3mhvP8je2D2Vhb56Js-E0=\" style=\"display: block; height: auto; border: 0; width: 200px; max-width: 100%;\" title=\"Image\" width=\"200\"/></div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "<td class=\"column column-2\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"66.66666666666667%\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"text_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"padding-bottom:10px;padding-left:30px;padding-right:10px;padding-top:25px;\">\n"
                    + "<div style=\"font-family: sans-serif\">\n"
                    + "<div class=\"txtTinyMce-wrapper\" style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #85D874; line-height: 1.2; font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\">\n"
                    + "<p style=\"margin: 0; font-size: 14px; color:#53e2f1; font-weight: bold;\">OUR DENTAL CLINIC</p>\n"
                    + "</div>\n"
                    + "</div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"text_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"padding-bottom:10px;padding-left:30px;padding-right:30px;padding-top:5px;\">\n"
                    + "<div style=\"font-family: sans-serif\">\n"
                    + "<div class=\"txtTinyMce-wrapper\" style=\"font-size: 12px; mso-line-height-alt: 18px; color: #283C4B; line-height: 1.5; font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\">\n"
                    + "<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 19.5px;\"><span style=\"font-size:13px;\">Our Dental Clinic is proud to be one of the \"Prestige - Quality\" ones in Ho Chi Minh City today. With a team of highly qualified doctors, many years of experience in the field of dentistry, graduated from prestigious Universities.</span></p>\n"
                    + "<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 19.5px;\"><span style=\"font-size:13px;\"></span></p>\n"
                    + "</div>\n"
                    + "</div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-6\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #000000; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<table border=\"0\" cellpadding=\"25\" cellspacing=\"0\" class=\"text_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<div style=\"font-family: sans-serif\">\n"
                    + "<div class=\"txtTinyMce-wrapper\" style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2; font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\">\n"
                    + "<p style=\"margin: 0; font-size: 14px; text-align: left;\">Copyright @ Dental Clinic - " + new Date(System.currentTimeMillis()) + "</p>\n"
                    + "</div>\n"
                    + "</div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-7\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<div class=\"spacer_block\" style=\"height:30px;line-height:30px;font-size:1px;\"> </div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-8\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"icons_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"vertical-align: middle; color: #9d9d9d; font-family: inherit; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;\">\n"
                    + "<table cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"vertical-align: middle; text-align: center;\">\n"
                    + "<!--[if vml]><table align=\"left\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;\"><![endif]-->\n"
                    + "<!--[if !vml]><!-->\n"
                    + "<table cellpadding=\"0\" cellspacing=\"0\" class=\"icons-inner\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; margin-right: -4px; padding-left: 0px; padding-right: 0px;\">\n"
                    + "<!--<![endif]-->\n"
                    + "<tr>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table><!-- End -->\n"
                    + "</body>\n"
                    + "</html>";
            message.setSubject("Appointment confirmation email");
            message.setContent(msg, "text/html");

            //3rd step)send message  
            Transport.send(message);

            System.out.println("Done");

        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }

    }

    public void sendActivateLink(Customer customer) {

        final String user = "vinhlgse161135@fpt.edu.vn";//change accordingly  
        final String pass = "wzducphbhryilmko";//change accordingly  

        //1st step) Get the session object    
        Properties props = new Properties();
        props.setProperty("mail.smtp.host", "smtp.gmail.com");//change accordingly  
        props.setProperty("mail.smtp.port", "587");
        props.setProperty("mail.smtp.auth", "true");
        props.setProperty("mail.smtp.starttls.enable", "true");

        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(user, pass);
            }
        });
        //2nd step)compose message  
        try {
            //create link
            long sendTime = System.currentTimeMillis();
            String link = "http://localhost:8080/dentalclinic/ActivateAccount?idHash=" + customer.getIdHash();

            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(user));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(customer.getEmail()));

            String msg = "<!DOCTYPE html>\n"
                    + "\n"
                    + "<html lang=\"en\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:v=\"urn:schemas-microsoft-com:vml\">\n"
                    + "<head>\n"
                    + "<title></title>\n"
                    + "<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n"
                    + "<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>\n"
                    + "<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->\n"
                    + "<style>\n"
                    + "		* {\n"
                    + "			box-sizing: border-box;\n"
                    + "		}\n"
                    + "\n"
                    + "		body {\n"
                    + "			margin: 0;\n"
                    + "			padding: 0;\n"
                    + "		}\n"
                    + "\n"
                    + "		a[x-apple-data-detectors] {\n"
                    + "			color: inherit !important;\n"
                    + "			text-decoration: inherit !important;\n"
                    + "		}\n"
                    + "\n"
                    + "		#MessageViewBody a {\n"
                    + "			color: inherit;\n"
                    + "			text-decoration: none;\n"
                    + "		}\n"
                    + "\n"
                    + "		p {\n"
                    + "			line-height: inherit\n"
                    + "		}\n"
                    + "\n"
                    + "		.desktop_hide,\n"
                    + "		.desktop_hide table {\n"
                    + "			mso-hide: all;\n"
                    + "			display: none;\n"
                    + "			max-height: 0px;\n"
                    + "			overflow: hidden;\n"
                    + "		}\n"
                    + "\n"
                    + "		@media (max-width:620px) {\n"
                    + "			.desktop_hide table.icons-inner {\n"
                    + "				display: inline-block !important;\n"
                    + "			}\n"
                    + "\n"
                    + "			.icons-inner {\n"
                    + "				text-align: center;\n"
                    + "			}\n"
                    + "\n"
                    + "			.icons-inner td {\n"
                    + "				margin: 0 auto;\n"
                    + "			}\n"
                    + "\n"
                    + "			.row-content {\n"
                    + "				width: 100% !important;\n"
                    + "			}\n"
                    + "\n"
                    + "			.mobile_hide {\n"
                    + "				display: none;\n"
                    + "			}\n"
                    + "\n"
                    + "			.stack .column {\n"
                    + "				width: 100%;\n"
                    + "				display: block;\n"
                    + "			}\n"
                    + "\n"
                    + "			.mobile_hide {\n"
                    + "				min-height: 0;\n"
                    + "				max-height: 0;\n"
                    + "				max-width: 0;\n"
                    + "				overflow: hidden;\n"
                    + "				font-size: 0px;\n"
                    + "			}\n"
                    + "\n"
                    + "			.desktop_hide,\n"
                    + "			.desktop_hide table {\n"
                    + "				display: table !important;\n"
                    + "				max-height: none !important;\n"
                    + "			}\n"
                    + "		}\n"
                    + "	</style>\n"
                    + "</head>\n"
                    + "<body style=\"background-color: #283C4B; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"nl-container\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #283C4B;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<div class=\"spacer_block\" style=\"height:20px;line-height:20px;font-size:1px;\"> </div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-2\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #283C4B;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #333; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-left: 15px; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"image_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"width:100%;padding-right:0px;padding-left:0px;\">\n"
                    + "<div style=\"line-height:10px\"><img alt=\"Image\" src=\"https://static.crozdesk.com/web_app_library/providers/logos/000/012/527/box/doccure-1618394200-logo.png?1618394200\" style=\"display: block; height: 120px; border: 0; width: 150px; max-width: 100%;\" title=\"Image\" width=\"236\"/></div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-3\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #283C4B;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #53e2f1; color: #333; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-left: 10px; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"text_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:30px;\">\n"
                    + "<div style=\"font-family: sans-serif\">\n"
                    + "<div class=\"txtTinyMce-wrapper\" style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #FFFFFF; line-height: 1.2; font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\">\n"
                    + "<p style=\"margin: 0; font-size: 18px; text-align: left;\"><span style=\"font-size:24px; font-weight: bolder;\">Hello "+customer.getPersonalName()+",</span></p>\n"
                    + "<p style=\"margin: 0; font-size: 18px; text-align: left;\"><span style=\"font-size:24px;\">This is your activate account email! </span><br/></p>\n"
                    + "</div>\n"
                    + "</div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-4\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #283C4B;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #333; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-top: 0px; padding-bottom: 10px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"button_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"padding-bottom:0px;padding-left:30px;padding-right:10px;padding-top:10px;text-align:center;\">\n"
                    + "<!--[if mso]><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"\" style=\"height:44px;width:123px;v-text-anchor:middle;\" arcsize=\"0%\" strokeweight=\"0.75pt\" strokecolor=\"#85D874\" fillcolor=\"#FFFFFF\"><w:anchorlock/><v:textbox inset=\"0px,0px,0px,0px\"><center style=\"color:#85D874; font-family:Arial, sans-serif; font-size:16px\"><![endif]--><a href=\""+link+"\" style=\"text-decoration:none;display:inline-block;color:#53e2f1;background-color:#FFFFFF;border-radius:0px;width:auto;border-top:1px solid #53e2f1;font-weight:undefined;border-right:1px solid #53e2f1;border-bottom:1px solid #53e2f1;border-left:1px solid #53e2f1;padding-top:5px;padding-bottom:5px;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;\" target=\"_blank\"><span style=\"padding-left:20px;padding-right:20px;font-size:16px;display:inline-block;letter-spacing:normal;\"><span style=\"font-size: 16px; line-height: 2; word-break: break-word; mso-line-height-alt: 32px;\">Activate Account</span></span></a>\n"
                    + "<!--[if mso]></center></v:textbox></v:roundrect><![endif]-->\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-5\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #F6F6F6; color: #333; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"33.333333333333336%\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"image_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"width:100%;padding-right:0px;padding-left:0px;padding-top:5px;\">\n"
                    + "<div align=\"center\" style=\"line-height:10px\"><img alt=\"Image\" src=\"https://media.istockphoto.com/photos/dentists-office-in-barcelona-medical-workers-portrait-picture-id687663822?k=20&m=687663822&s=612x612&w=0&h=rKaLezUTRp6ovaVbycpTLI3mhvP8je2D2Vhb56Js-E0=\" style=\"display: block; height: auto; border: 0; width: 200px; max-width: 100%;\" title=\"Image\" width=\"200\"/></div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "<td class=\"column column-2\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"66.66666666666667%\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"text_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"padding-bottom:10px;padding-left:30px;padding-right:10px;padding-top:25px;\">\n"
                    + "<div style=\"font-family: sans-serif\">\n"
                    + "<div class=\"txtTinyMce-wrapper\" style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #85D874; line-height: 1.2; font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\">\n"
                    + "<p style=\"margin: 0; font-size: 14px; color:#53e2f1; font-weight: bold;\">OUR DENTAL CLINIC</p>\n"
                    + "</div>\n"
                    + "</div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"text_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"padding-bottom:10px;padding-left:30px;padding-right:30px;padding-top:5px;\">\n"
                    + "<div style=\"font-family: sans-serif\">\n"
                    + "<div class=\"txtTinyMce-wrapper\" style=\"font-size: 12px; mso-line-height-alt: 18px; color: #283C4B; line-height: 1.5; font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\">\n"
                    + "<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 19.5px;\"><span style=\"font-size:13px;\">Our Dental Clinic is proud to be one of the \"Prestige - Quality\" ones in Ho Chi Minh City today. With a team of highly qualified doctors, many years of experience in the field of dentistry, graduated from prestigious Universities.</span></p>\n"
                    + "<p style=\"margin: 0; font-size: 12px; mso-line-height-alt: 19.5px;\"><span style=\"font-size:13px;\"></span></p>\n"
                    + "</div>\n"
                    + "</div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-6\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF; color: #000000; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<table border=\"0\" cellpadding=\"25\" cellspacing=\"0\" class=\"text_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<div style=\"font-family: sans-serif\">\n"
                    + "<div class=\"txtTinyMce-wrapper\" style=\"font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2; font-family: Arial, Helvetica Neue, Helvetica, sans-serif;\">\n"
                    + "<p style=\"margin: 0; font-size: 14px; text-align: left;\">Copyright @ Dental Clinic</p>\n"
                    + "</div>\n"
                    + "</div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-7\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<div class=\"spacer_block\" style=\"height:30px;line-height:30px;font-size:1px;\"> </div>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-8\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td>\n"
                    + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 600px;\" width=\"600\">\n"
                    + "<tbody>\n"
                    + "<tr>\n"
                    + "<td class=\"column column-1\" style=\"text-align: left; mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\n"
                    + "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"icons_block\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"vertical-align: middle; color: #9d9d9d; font-family: inherit; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;\">\n"
                    + "<table cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\n"
                    + "<tr>\n"
                    + "<td style=\"vertical-align: middle; text-align: center;\">\n"
                    + "<!--[if vml]><table align=\"left\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;\"><![endif]-->\n"
                    + "<!--[if !vml]><!-->\n"
                    + "<table cellpadding=\"0\" cellspacing=\"0\" class=\"icons-inner\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; margin-right: -4px; padding-left: 0px; padding-right: 0px;\">\n"
                    + "<!--<![endif]-->\n"
                    + "\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table>\n"
                    + "</td>\n"
                    + "</tr>\n"
                    + "</tbody>\n"
                    + "</table><!-- End -->\n"
                    + "</body>\n"
                    + "</html>";
            message.setSubject("Account Activation Email");
            message.setContent(msg, "text/html");

            //3rd step)send message  
            Transport.send(message);

            System.out.println("Done");

        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }

    }

}
